reg/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name='reg'
urlpatterns = [
    path('signup/', views.user_signup, name = 'user_signup'),
    path('signup/account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),
    path('profile/', views.user_profile, name='user_profile'),
    path('profile/edit/', views.user_profile_edit, name='user_profile_edit'),
    path('profile/profile_pic_update/', views.user_profile_pic_update, name='user_profile_pic_update'),
    path('', views.index, name='index'),
]

userprofile/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='reg/user_login.html',extra_context={'next':'/'}), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('', include('reg.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reg/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser, BaseUserManager

# Create your models here.

class UserManger(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("email address is mandatory")
        user = self.model(
            email = self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using = self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email, password=password)
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        print("Creating Super user using the provided method")
        user.save(using = self._db)
        return user

class User(AbstractBaseUser, PermissionsMixin):
    phone_regex = RegexValidator(regex = r'^(\+\d{1,3}[- ]?)?\d{10}$', message="Indian mobile number. Include +91-")

    first_name = models.CharField(max_length=100, blank=True, default='user')
    last_name = models.CharField(max_length=50, blank=True,)
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True,)
    mobile_number = models.CharField(validators=[phone_regex], max_length=15)
    gender = models.CharField(max_length=10)
    dob = models.DateField(null=True, blank=True)
    profile_pic = models.ImageField(upload_to='uploads/', default='images/blank-profile-pic.png')
    date_joined = models.DateField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManger()

    USERNAME_FIELD = 'email'

    EMAIL_FIELD = 'email'

    REQUIRED_FIELDS = []

    def email_user(self,subject, message, from_email=None, **kwargs):
        from_email = settings.EMAIL_HOST_USER
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return self.email

reg/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField, UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ("email",)

class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
       super(ProfileForm, self).__init__(*args, **kwargs)
       for field in self.fields:
           self.fields[field].widget.attrs['readonly'] = True
    class Meta:
        model = get_user_model()
        fields = ('profile_pic','first_name','last_name','email','mobile_number','gender','dob')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name','last_name','mobile_number','gender','dob')
        labels = {'first_name':'First Name', 'last_name':'Last Name', 'mobile_number':'Mobile Number', 'gender':'Gender', 'dob':'Date of Birth'}
        help_texts = {'mobile_number':'Indian Number. Include +91-', 'dob':'mm/dd/YYYY'}
        GENDER_CHOICES = (
            ('','--select--'),
            ('M', 'Male'),
            ('F', 'Female'),
        )
        widgets = {
            'gender' : forms.Select(choices = GENDER_CHOICES),
        }

class ProfilePicForm(forms.Form):
    image_file = forms.ImageField()

reg/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.decorators import login_required
from .tokens import account_activation_token
from .forms import SignupForm, ProfileForm, ProfileEditForm, ProfilePicForm
from django.contrib.auth import get_user_model
import json


# Create your views here.

def index(request):
    return render(request, 'reg/index.html')

def user_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            try:
                password = form.clean_password2()
            except Exception as e:
                error_message = str(e)
                return render(request, 'reg/user_signup.html',{'form':form, 'error_message':error_message})
            user = form.save()
            current_site = get_current_site(request)
            subject = 'Activate your account'
            message = render_to_string('reg/account_activation_mail.html',{'user':user, 'domain':current_site.domain, 'uid':urlsafe_base64_encode(force_bytes(user.pk)),'token':account_activation_token.make_token(user)})
            user.email_user(subject,message)
            return redirect('reg:account_activation_sent')
        else:
            errors = json.loads(form.errors.as_json())
            for field, error in errors.items():
                error_message = error[0]['message']
                if field == 'email':
                    break
            return render(request, 'reg/user_signup.html',{'form':form, 'error_message':error_message})
    else:
        form = SignupForm()
        return render(request, 'reg/user_signup.html',{'form':form})

def account_activation_sent(request):
    return render(request,'reg/account_activation_sent.html')

def activate(request, uid64, token):
    try :
        uid = force_text(urlsafe_base64_decode(uid64))
        user = get_user_model().objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.joined_date = timezone.now()
        user.save()
        return redirect('login')
    else:
        return render(request, 'reg/account_activation_invalid.html')

@login_required
def user_profile(request):
        usr = request.user
        user = get_user_model().objects.get(email=usr)
        form = ProfileForm(instance=user)
        return render(request, 'reg/user_profile.html', {'form':form})

@login_required
def user_profile_edit(request):
    usr = request.user
    user = get_user_model().objects.get(email=usr)
    if request.method == 'POST':
        form = ProfileEditForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save()
            return redirect('reg:user_profile')
        # else:
            # print(form.errors)
            # errors = json.loads(form.errors.as_json())
            # for field, error in errors.items():

    else:
        form = ProfileEditForm(instance=user)
    return render(request, 'reg/user_profile_edit.html', {'form':form})

@login_required
def user_profile_pic_update(request):
    usr = request.user
    user = get_user_model().objects.get(email=usr)
    if request.method == 'POST':
        form = ProfilePicForm(request.POST, request.FILES)
        if form.is_valid():
            image_file = form.cleaned_data['image_file']
            user.profile_pic = image_file
            user.save()
            return redirect('reg:user_profile')
        else:
            print(form.errors)
    else:
        form = ProfilePicForm()
        return render(request, 'reg/user_profile_pic_update.html', {'form':form})
    

reg/templates/reg/account_activation_invalid.html
{% extends 'registration/base.html' %}

{% block content %}
    <p><strong>Sorry!!</strong> Your account activation is invalid. Please try to signup again.</p>
{% endblock %}

reg/templates/reg/account_activation_mail.html
{% autoescape off %}
Hi {{ user.email }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'reg:activate' uid64=uid token=token %}
{% endautoescape %}

reg/templates/reg/account_activation_sent.html
{% extends 'reg/base.html' %}

{% block content %}
<div align='center' class='home-body'>
    <p>Please check your email. We have sent you an activation link for your account.</p>
</div>
{% endblock %}

reg/templates/reg/base.html
{% load static %}
<html>
    <head>
        <title>Registration</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <div>
            {% if user.is_authenticated %}
                <div style="float:right;padding-top:20px;padding-right:20px">
                    <a href="{% url 'logout' %}"><button class='btn btn-default'>Logout</button></a>
                </div>
            {% endif %}
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

reg/templates/reg/index.html
{% extends 'reg/base.html' %}

{% block content %}
    <div class='home-body' align='center'>
        <h1>Welcome to my Blogging World!!</h1>
        <br><br>
        {% if not user.is_authenticated %}
            <a href="{% url 'reg:user_signup' %}">SignUp</a>
            &nbsp;&nbsp;&nbsp;
            <a href="{% url 'login' %}">Login</a>
        {% else %}
            <a href="{% url 'reg:user_profile' %}"><button class='btn btn-default'>View Profile</button></a>
        {% endif %}
    </div>  

{% endblock %}

reg/templates/reg/user_login.html
{% extends "reg/base.html" %}

{% block content %}
<div class="row post-form-full-body">
        <div class="col-sm-4"></div>
        <div class="col-sm-4 post-form">
            <br>
            {% if form.errors %}
                <p style="color:red;"><small>Your username and password didn't match. Please try again.</small></p>
            {% endif %}  
            
            <form action="{% url 'login' %}" method='POST'>
                {% csrf_token %}
                <table align='center'>
                    {% for field in form %}
                        <tr>
                            <td align='right'>{{ field.label_tag }}</td>
                            <td>&nbsp;{{ field }}</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td><input type="hidden" name="next" value="{{ next }}" /></td>
                        <td><button class='btn btn-default' type='submit'>Login</button></td>
                    </tr>
                </table>
            </form>
        </div>
        <div class="col-sm-4"></div>
    </div>
{% endblock %}

reg/templates/reg/user_profile.html
{% extends 'reg/base.html' %}

{% block content %}
<div class="row post-form-full-body">
    <div class="col-sm-4"></div>
    <div class="col-sm-4 post-form">
        <div align='center'>
            <br>
            <div class='profile-pic'>
                <img src="{{ form.instance.profile_pic.url }}" height=120 width=100>
            </div>
            <br>
            <div>
                <a href="{% url 'reg:user_profile_edit' %}"><button class='btn btn-default'>Edit Profile</button></a>
                <a href="{% url 'reg:user_profile_pic_update' %}"><button class='btn btn-default'>Profile Pic</button></a>
            </div>
            <hr>
            <div>
                {% if form.non_field_errors %}
                    <div>
                        <p>{{ form.non_field_errors }}</p>
                    </div>
                {% endif %}
                <table align='center'>
                    {% if form.first_name.errors %}
                        <tr>
                            <td>{{ form.first_name.errors }}</td>
                        </tr>
                    {% endif %}
                    <tr>
                        <td align='right'><label for="{{ form.first_name.id_for_label }}">First Name : </label></td>
                        <td>&nbsp;</td>
                        <td>{{ form.first_name.value }}</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                    </tr>
                    {% if form.last_name.errors %}
                        <tr>
                            <td>{{ form.last_name.errors }}</td>
                        </tr>
                    {% endif %}
                    <tr>
                        <td align='right'><label for="{{ form.last_name.id_for_label }}">Last Name : </label></td>
                        <td>&nbsp;</td>
                        <td>{{ form.last_name.value }}</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                    </tr>
                    {% if form.mobile_number.errors %}
                        <tr>
                            <td>{{ form.mobile_number.errors }}</td>
                        </tr>
                    {% endif %}
                    <tr>
                        <td align='right'><label for="{{ form.mobile_number.id_for_label }}">Mobile Number : </label></td>
                        <td>&nbsp;</td>
                        <td>{{ form.mobile_number.value }}</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                    </tr>
                    {% if form.email.errors %}
                        <tr>
                            <td>{{ form.email.errors }}</td>
                        </tr>
                    {% endif %}
                    <tr>
                        <td align='right'><label for="{{ form.email.id_for_label }}">Email : </label></td>
                        <td>&nbsp;</td>
                        <td>{{ form.email.value }}</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                    </tr>
                    {% if form.gender.errors %}
                        <tr>
                            <td>{{ form.gender.errors }}</td>
                        </tr>
                    {% endif %}
                    <tr>
                        <td align='right'><label for="{{ form.gender.id_for_label }}">Gender : </label></td>
                        <td>&nbsp;</td>
                        {% if form.gender.value == "M" %}
                            <td>Male</td>
                        {% elif form.gender.value == "F" %}
                            <td>Female</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                    </tr>
                    {% if form.dob.errors %}
                        <tr>
                            <td>{{ form.dob.errors }}</td>
                        </tr>
                    {% endif %}
                    <tr>
                        <td align='right'><label for="{{ form.dob.id_for_label }}">Date of Birth : </label></td>
                        <td>&nbsp;</td>
                        <td>{{ form.dob.value }}</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-sm-4"></div>
</div>
{% endblock %}

reg/templates/reg/user_profile_edit.html
{% extends 'reg/base.html' %}

{% block content %}
<div class="row post-form-full-body">
    <div class="col-sm-4"></div>
    <div class="col-sm-4 post-form">
        <div align='center'>
            <br>
            <div class='profile-pic'>
                <img src="{{ form.instance.profile_pic.url }}" height=120 width=100>
            </div>
            <br>
            <div>
                <a href="{% url 'reg:user_profile_pic_update' %}"><button class='btn btn-default'>Profile Pic</button></a>
            </div>
            <hr>
            <div>
                <form action="{% url 'reg:user_profile_edit' %}" method='POST'>
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        <div>
                            <p>{{ form.non_field_errors }}</p>
                        </div>
                    {% endif %}
                    <table align='center'>
                        {% for field in form %}
                            <tr>
                                <td align='right'>{{ field.label_tag }}</td>
                                <td>&nbsp;&nbsp;{{ field }}</td>
                            </tr>
                            {% if field.help_text %}
                                <tr>
                                    <td></td>
                                    <td>&nbsp;&nbsp;<small>{{ field.help_text }}</small></td>
                                </tr>
                            {% endif %}
                            {% if field.errors %}
                                <tr>
                                    <td></td>
                                    <td style="color:red;"><small>{{ field.errors.as_text }}</small></td>
                                </tr>
                            {% endif %}
                            <tr>
                                <td>&nbsp;</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td><button class='btn btn-default' type='submit'>Save</button></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
    <div class="col-sm-4"></div>
</div>
{% endblock %}

reg/templates/reg/user_profile_pic_update.html
{% extends 'reg/base.html' %}

{% block content %}
<div class="row post-form-full-body">
    <div class="col-sm-4"></div>
    <div class="col-sm-4 post-form">
        <br>
        <div align='center' class='profile-pic'>
            <img src="" height=200 width=150>
        </div>
        <br><br>
        <div>
            <form action="{% url 'reg:user_profile_pic_update' %}" method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                <table align='right'>
                    <tr>
                        <td><input type='file' name='image_file'></td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                    </tr>
                </table>
                <table align='center'>
                    <tr>
                        <td><button type='submit'>Upload</button></td>
                        <td>&nbsp;</td>
                        <td><button>Preview</button></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
    <div class="col-sm-4"></div>
</div>
{% endblock %}

reg/templates/reg/user_signup.html
{% extends 'reg/base.html' %}

{% block content %}
    <div class="row post-form-full-body">
        <div class='col-sm-4'></div>
        <div class='post-form col-sm-4'>
            <table align='center'>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    {% if error_message %}
                            <td style="color:red"><small>* {{ error_message }}</small></td>
                    {% endif %}
                </tr>
            </table>
            <form action="{% url 'reg:user_signup' %}" method='POST'>
                {% csrf_token %}
                <table align='center'>
                    {% for field in form %}
                        <tr>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td>{{ field.label_tag }}</td>
                            <td>{{ field }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><button class="btn btn-default" type="submit">Sign up</button></td>
                    </tr>
                </table>
            </form>
        </div>
        <div class='col-sm-4'></div>
    </div> 
{% endblock %}